name: ruff
permissions:
  contents: read
  
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/ruff-action@v4.0.0
      - run: ruff check
      