name: ruff
permissions:
  contents: read
  
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: chartboost/ruff-action@v1
      